### ISSUE TITLE
Add config option to enable/disable brotli/gzip

### ISSUE THREAD

**Issue by redwerkz** [sondr3/astro-compressor#7]
Add a config to create just the sidecar files needed could be a useful feature for this plugin.

Depending on your webserver there may be only `gzip` available. In fact `nginx` provides official support for `brotli` only for their paying users of `nginx plus`. Open-source edition needs to manually load that module.

[Using Brotli Compression in NGINX](https://requestmetrics.com/web-performance/brotli-nginx)

**Comment by sondr3** [comment]
Sure, I'll add it in the next few days. I'm not sure it hurts to have brotli files generated but I agree options would be useful.

**Comment by sondr3** [comment]
Done in [3472d07](3472d07de4c46fc91b5951679b41bdb48cf8f83d)

**Comment by redwerkz** [comment]
> Sure, I'll add it in the next few days. I'm not sure it hurts to have brotli files generated but I agree options would be useful.

Put it in the right perspective: In the long-run it's a huge waste of processing power etc. 🫣
